# Generated by Django 5.2.3 on 2025-07-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coach_coach_type_train_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_type',
        ),
        migrations.RemoveField(
            model_name='train',
            name='number',
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train'),
        ),
    ]
