# Generated by Django 5.2.3 on 2025-07-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_coach_coach_type_remove_train_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defect',
            name='title',
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC 1 Tier'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='train',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='core.train'),
        ),
    ]
