# Generated by Django 5.2.3 on 2025-07-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_defect_description_remove_defect_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC 1 Tier'), ('GEN', 'General')], default='GEN', max_length=10),
        ),
    ]
