# Generated by Django 5.2.3 on 2025-07-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_coach_coach_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(blank=True, choices=[('SL', 'Sleeper'), ('3A', 'AC 3 Tier'), ('2A', 'AC 2 Tier'), ('1A', 'AC 1 Tier'), ('GEN', 'General')], max_length=10, null=True),
        ),
    ]
