# Generated by Django 5.2.3 on 2025-07-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coach_coach_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_type',
        ),
        migrations.RemoveField(
            model_name='train',
            name='number',
        ),
        migrations.AddField(
            model_name='defect',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train'),
        ),
    ]
