# Generated by Django 5.2.3 on 2025-07-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_coach_coach_type_remove_train_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(default='Sleeper', max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='number',
            field=models.CharField(default='00000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='core.train'),
        ),
    ]
