# Generated by Django 5.2.3 on 2025-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coach_coach_type_train_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
