# Generated by Django 5.2.3 on 2025-07-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_train_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3-Tier'), ('2A', 'AC 2-Tier'), ('1A', 'AC First Class'), ('GEN', 'General'), ('CC', 'Chair Car'), ('EC', 'Executive Chair Car')], default='SL', max_length=10),
        ),
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
