# Generated by Django 5.2.3 on 2025-07-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_coach_coach_number_alter_coach_coach_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='core.train'),
        ),
    ]
